### ISSUE TITLE
bdecode variant without erroring on long string?

### ISSUE THREAD

**Issue by itdaniher** [whtsky/bencoder.pyx#5]
Doing some hacking on @boramalper's  [magnetico](https://github.com/boramalper/magnetico).

It relies on data present at the end of a bencoded bytestring. In order to use bencoder.pyx I had to patch out https://github.com/whtsky/bencoder.pyx/blob/master/bencoder.pyx#L96 and return both `r` and `l`.

See https://github.com/boramalper/magnetico/blob/master/magneticod/magneticod/bencode.py#L53 for the function for which I needed to add a replacement.

Would this project accept a PR adding a bdecode2 returning both r and l, and not erroring on excess data?

Thanks!

**Comment by whtsky** [comment]
Yes.
